name: Python Test
on: [workflow_dispatch, workflow_call]
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Virtual Environment
        run: |
          python3 -m pip install --user virtualenv
          virtualenv env_unit_tests
          source ./env_unit_tests/bin/activate

      - name: Install Dependencies
        run: |
          pip install -r ./aws-chatgpt-telegram/lambda_function/requirements.txt
          
      - name: Run Unit Tests
        run: |
          python -m unittest unittests.py
        working-directory: ./aws-chatgpt-telegram/lambda_function/
        env:
          TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"
          OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
          TELEGRAM_SECRET_TOKEN: "${{ secrets.TELEGRAM_SECRET_TOKEN }}"